### ISSUE TITLE
Edit of temporal information of georeference won't save

### ISSUE THREAD

**Issue by lodewijk81** [kleiolab/geovistory-feedback#4] opened 2019-06-17 13:41 UTC
**Describe the bug**
I'm trying to edit the dates related to the georeference of a built work. Everything seems to be OK, but after the reloading the page, it appear that the new dates were not saved (the old ones are shown).

**To Reproduce**
See short video [here](https://www.dropbox.com/s/4708asdxft8emrt/Schermopname%202019-06-17%20om%2015.35.23.mov?dl=0).

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser Chrome 74.0.3729.169

**Comment by joschne** [comment] 2019-06-18 06:36
thank you @lodewijk81 for the video. I can reproduce it and confirm that it is a bug. With the next version this should be fixed.

**Comment by joschne** [comment] 2019-06-18 17:16
the issue is solved.

**Closed by joschne** 2019-06-18 17:16 UTC
Labels: bug
